language: node_js
node_js:
  - 'lts/*'
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: pretest
      before_script: skip
      script: commitlint-travis
      after_failure: skip
    - stage: test
      env: BROWSER=chrome
      addons:
        chrome: stable
    - stage: test
      env: BROWSER=firefox
      addons:
        firefox: latest
      # Codecs needed for Firefox to play audio.
      before_install: sudo apt-get install -y ubuntu-restricted-addons
    - stage: deploy
      if: branch = master && type != pull_request
      before_script: skip
      script: npm run build
      after_failure: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: bash deploy.sh
before_script:
  # Build budle.js
  - npm run build
  - cp test/setup.js.travis test/setup.js
  # Start https server (and sleep) so we can get the local bundle.js via https.
  # The `&` at the end tells this process to fork into the background
  # https://github.com/travis-ci/travis-ci/issues/1321
  - npm run live-serve-build &
  # Increase the shared memory mountpoint. Chrome or something in the tests is
  # taking up more shared memory than is available which causes tests to fail.
  # See https://github.com/SeleniumHQ/docker-selenium/issues/431
  - sudo mount -o remount,size=64G /run/shm
sudo: required
script: npm test -- --bail
# When the test script fails, push screen shots to a git branch.
after_failure: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR/travis-screenshots"
    git init
    git checkout -b travis-screenshots
    git add .
    git -c user.name="$GITHUB_USER" -c user.email='travis' commit -m 'Travis CI screenshots'
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG travis-screenshots 2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
